spring.application.name=api-usuarios

server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5432/bd_apiusuarios
spring.datasource.username=user_apiusuarios
spring.datasource.password=pass_apiusuarios
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cors.allowed.origins=http://localhost:4200,http://localhost:3000

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_rabbit
spring.rabbitmq.password=pass_rabbit
spring.rabbitmq.virtual-host=/

spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000